path:
    train_path: datasets/klue-sts-v1.1_train_ri_augset.json
    dev_path: datasets/klue-sts-v1.1_dev.json
    test_path: datasets/klue-sts-v1.1_dev.json

data:
    shuffle: True
    augmentation: True
    max_length : 128

model:
  model_name: 'klue/roberta-base'
  saved_name: 'eda_random_insertion_model'

train:
  seed: 2023
  batch_size: 32
  max_epoch: 5
  learning_rate: 1e-5
  logging_step: 100
  drop_out: 0.1
  warmup_ratio: 0.1
  weight_decay: 0.1
  
runner:
  options:
    num_workers: 8